const description = 'Penny Skateboards are built with the highest quality raw materials and fanatical attention to detail.';
const products = [
  {
    _id: "1",
    name: 'Blue',
    image: '/images/pb-blue.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 89.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: 'Black',
    image: '/images/pb-black.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 599.99,
    countInStock: 10,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: 'Grey',
    image: '/images/pb-grey.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: 'Light Green',
    image: '/images/pb-light-green.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "5",
    name: 'Mint',
    image: '/images/pb-mint.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "6",
    name: 'Olive',
    image: '/images/pb-olive.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "7",
    name: 'Orange',
    image: '/images/pb-orange.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "8",
    name: 'Pink',
    image: '/images/pb-pink.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "9",
    name: 'Red',
    image: '/images/pb-red.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "10",
    name: 'Yellow',
    image: '/images/pb-yellow.jpeg',
    description:
      description,
    brand: 'Penny',
    category: 'Penny',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
]

export default products;